version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - ls
      - npm install -g serverless
  build:
    commands:
      - npm install --only=stg
  post_build:
    commands:
      - serverless deploy --stage stg --package serverless --verbose