service:
  name: To Do List 

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  versionFunctions: false
  timeout: 3
  memorySize: 128
  environment:
    SERVERLESS_STAGE: test
  stackTags:
    
custom:
  defaultStage: dev
  suffix : "Function"
package:
  individually: true

functions:
  todoList:
    handler: todoList/todoList.handler
    description: "To Do List"
    events:
      - http:
          method: get
          path: todoList
          request:
            parameters:
              path:
                function: true
          cors: true
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-stack-output
  - serverless-plugin-simulate
  - serverless-kms-secrets
  